In [203]:
import optbinning
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, RepeatedStratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, precision_recall_curve, auc
from sklearn.feature_selection import f_classif
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from scipy.stats import chi2_contingency
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score, classification_report
from tqdm import tqdm



from datetime import datetime

In [204]:
df = pd.read_excel('fin_data_of_proj.xlsx')

In [205]:
df

,gara_id,application_name,author_id,builder_id,contractor_id,designer_id,engine_id,manager_id,status,decision_date,region_name,city_id,type,turn,network,period_month,start_date,end_date,class,flat_area,build_qty,build_floor,build_area,com_area,park_area,flat_qty,com_qty,park_qty,flat_onerm,flat_tworm,flat_threerm,flat_fourrm,cost_plan,flat_msprice,build_mscost,flat_mscost,com_msprice,park_price,self_cost,unfin_cost,share_cost,warr_cost,comm_cost,cost_official,flat_inner,flat_height,dpg_date,dpg_num,dpg_add_num,dpg_num_text,prolongation,update_date,state_id,create_date,annul_date,state_name,дата фин данных,bin,date,Итого краткосрочные активы,Итого краткосрочных обязательств,Денежные средства,Краткосрочная дебиторская задолженность,Запасы,Себестоимость,Доход от реализации,Итого активы,Итого капитал,Итого пассивы,Краткосрочная кредиторская задолженность,Операционная прибыль,Долгосрочные финансовые обязательства,Краткосрочные финансовые обязательства,Итоговая прибыль (убыток),Расходы на финансирование,Коэффициент текущей ликвидности,Коэффициент быстрой ликвидности,Коэффициент абсолютной ликвидности,Коэффициент оборачиваемости запасов,Коэффициент оборачиваемости активов,Коэффициент оборачиваемости кредиторской задолженности,ROA,ROE,Коэффициент чистой прибыли,Коэффициент финансового левериджа,Коэффициент финансовой независимости,Коэффициент долговой нагрузки,Коэффициент долг на капитал,Коэффициент покрытия процентов,Покрытие долга,Target,life_cycle,today,real_life_cycle,percent_of_life_cycle,Target 2
0,729352,Заявка на гарантирование - 335,5.400012e+08,960340000376,9.603400e+11,0.000000e+00,2.210400e+11,1.904400e+11,NaN,NaT,г. Астана,18178,Стандартный,"5, 7",будут выполнены за счет застройщика,13.0,2022-11-03,2023-12-03,4,9633.70,NaN,9.0,9633.70,7631.20,313.30,96,2.0,NaN,16.0,34.0,32.0,NaN,2228233,360000.0,231.0,231295.0,400000.0,NaN,3.342349e+08,3.316000e+07,1.893998e+09,2.195073e+07,NaN,2228232541,предчистовая,2.7,2023-06-21,58,7.0,ДС7 21.06.23 к ДПГ-21-01-001/058,NaN,2024-06-04 14:03:30.466878,15320.0,2024-03-08 16:16:36.330524,NaN,Актуальная гарантия,2022-12-31,9.603400e+11,2022-12-31,1.694698e+08,5.837245e+07,1358342.81,6.282570e+06,1.189770e+07,3.297099e+07,6.312265e+07,5.893633e+08,5.063758e+08,5.893633e+08,2.368492e+07,1.062896e+08,2.308623e+07,7384225.12,1.217043e+08,18539551.20,2.903249,0.130899,0.023270,2.771208,0.107103,1.392067,0.206501,0.240344,1.928060,1.163885,0.859191,1.0,0.060174,5.733126,3.488284,0,395,2024-11-01,729,1.845570,0
1,790750,Заявка на гарантирование - 334,4.044001e+10,960340000376,9.603400e+11,0.000000e+00,2.210400e+11,1.904400e+11,NaN,NaT,г. Астана,18178,Стандартный,NaN,имеются,21.0,2022-11-03,2024-08-03,4,19350.28,NaN,12.0,19350.28,16324.11,1398.43,141,12.0,NaN,26.0,35.0,40.0,NaN,3413044920,330000.0,176382.0,176382.0,330000.0,NaN,5.119567e+08,4.913777e+08,2.901088e+09,2.921667e+07,NaN,3413044920,улучшенная черновая,2.7,2023-08-11,54,9.0,дс9 11.08.23 к ДПГ-21-01-001/054,NaN,2024-06-04 14:03:30.466878,15320.0,2024-03-08 16:16:36.330524,NaN,Актуальная гарантия,2022-12-31,9.603400e+11,2022-12-31,1.694698e+08,5.837245e+07,1358342.81,6.282570e+06,1.189770e+07,3.297099e+07,6.312265e+07,5.893633e+08,5.063758e+08,5.893633e+08,2.368492e+07,1.062896e+08,2.308623e+07,7384225.12,1.217043e+08,18539551.20,2.903249,0.130899,0.023270,2.771208,0.107103,1.392067,0.206501,0.240344,1.928060,1.163885,0.859191,1.0,0.060174,5.733126,3.488284,0,639,2024-11-01,729,1.140845,0
2,845821,Заявка на гарантирование - 407,8.034001e+10,60340004172,6.034000e+10,0.000000e+00,1.304400e+11,2.109400e+11,NaN,NaT,г. Шымкент,18277,Стандартный,NaN,иное,9.0,2023-06-12,2024-03-12,4,11723.00,NaN,9.0,11723.00,6650.80,1070.64,80,2.0,1635.0,8.0,40.0,24.0,NaN,2705190883,430000.0,230759.0,430000.0,450000.0,2000000.0,2.972323e+08,2.972323e+08,2.637281e+09,2.637281e+07,NaN,2934513361,чистовая,2.7,2023-09-14,151,1.0,ДПГ-23-13-050/151,NaN,2024-06-04 14:03:30.466878,15320.0,2024-03-08 16:16:36.330524,NaN,Актуальная гарантия,2022-12-31,6.034000e+10,2022-12-31,2.261012e+07,2.073661e+07,121449.24,1.328967e+07,5.785188e+06,2.816795e+07,3.102098e+07,2.802404e+07,4.024006e+06,2.802404e+07,3.933237e+06,2.057717e+06,2.739895e+06,1000000.00,1.941551e+06,98956.32,1.090348,0.646736,0.005857,4.868977,1.106941,7.161518,0.069282,0.482492,0.062588,6.964214,0.143591,1.0,0.929396,20.794199,0.550207,0,274,2024-11-01,508,1.854015,0
3,781580,Заявка на гарантирование - 379,5.114001e+10,981040003722,9.810400e+11,0.000000e+00,7.054001e+10,2.109400e+11,NaN,NaT,Актюбинская обл.,18267,Стандартный,NaN,будут выполнены за счет застройщика,14.0,2022-10-21,2023-12-21,3,6698.30,NaN,5.0,6698.30,4842.00,NaN,60,NaN,NaN,20.0,20.0,20.0,NaN,1226556104,267500.0,183114.0,242690.0,NaN,NaN,1.839834e+08,1.845334e+08,1.042573e+09,1.042023e+07,NaN,1226556104,чистовая,2.7,2023-07-04,144,NaN,ДПГ-23-04-063/144,NaN,2024-06-04 14:03:30.466878,15320.0,2024-03-08 16:16:36.330524,NaN,Актуальная гарантия,2022-12-31,9.810400e+11,2022-12-31,1.314323e+06,9.236130e+05,11793.00,6.769300e+04,1.202871e+06,1.005450e+06,1.072424e+06,1.334446e+06,4.108330e+05,1.334446e+06,8.427920e+05,4.661400e+04,0.000000e+00,8401.00,3.596800e+04,35.00,1.423023,0.086060,0.012768,0.835875,0.803647,1.192999,0.026954,0.087549,0.033539,3.248147,0.307868,1.0,0.020449,1331.828571,5.548625,0,426,2024-11-01,742,1.741784,0
4,746713,Заявка на гарантирование - 373,9.207400e+11,80440009616,8.044001e+10,0.000000e+00,2.208400e+11,2.202400e+11,NaN,NaT,г. Алматы,18194,Стандартный,4,имеются,10.0,2023-04-06,2024-01-06,4,4352.50,NaN,5.0,4352.50,2544.20,117.20,58,3.0,NaN,35.0,19.0,4.0,NaN,1084238076,455450.0,249106.0,285000.0,525000.0,NaN,1.084238e+08,2.277822e+08,9.758143e+08,8.564558e+06,NaN,1084238076,черновая,2.7,2023-07-21,133,1.0,дс1 к ДПГ-23-05-052/133,NaN,2024-06-04 14:03:30.466878,15320.0,2024-03-08 16:16:36.330524,NaN,Актуальная гарантия,2022-12-31,8.044001e+10,2022-12-31,1.263251e+06,2.647270e+05,924015.00,1.269090e+05,0.000000e+00,3.810000e+03,1.425000e+04,1.313339e+06,1.048612e+06,1.313339e+06,0.000000e+00,7.990000e+02,0.000000e+00,0.00,7.990000e+02,0.00,4.771901,3.969841,3.490445,inf,0.010850,inf,0.000608,0.000762,0.056070,1.252455,0.798432,1.0,0.000000,inf,inf,0,275,2024-11-01,575,2.090909,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,91,NaN,1.054000e+10,110540015593,9.706400e+11,NaN,1.304400e+11,1.703400e+11,Завершенный,2020-02-14,г. Астана,18178,Стандартный,6,NaN,16.0,2019-11-15,2021-02-10,4,12857.79,1.0,12.0,19814.66,1731.75,0.00,278,13.0,0.0,132.0,114.0,32.0,0.0,4490419686,295000.0,NaN,193717.0,350000.0,NaN,3.838444e+08,3.551541e+07,5.080042e+07,8.909808e+07,NaN,4490419686,черновая,2.7,2020-02-17,15,4.0,доп.согл.№4 к ДПГ-19-01-008/015,3.0,2024-02-26 09:00:35.388555,0.0,2024-03-08 16:16:36.330524,NaN,Гарантия выдана до 2023,2018-12-31,1.105400e+11,2018-12-31,1.551844e+06,1.790587e+06,26.00,7.364700e+05,4.669360e+05,7.888300e+04,1.041050e+05,7.551506e+06,6.354835e+05,7.551506e+06,6.280440e+05,6.984120e+05,8.789500e+04,0.00,5.645760e+05,0.00,0.866668,0.411315,0.000015,0.168937,0.013786,0.125601,0.074763,0.888420,5.423140,11.883087,0.084153,1.0,0.138312,inf,7.945981,1,453,2024-11-01,1813,4.002208,0
218,84,NaN,NaN,50440002386,5.044000e+10,NaN,3.114000e+10,1.706400e+11,Завершенный,2021-06-28,Атырауская обл.,18264,Стандартный,NaN,Наружные сети будут подведены Застройщиком за ...,7.0,2021-02-07,2022-02-18,3,4925.30,1.0,9.0,6326.20,0.00,0.00,72,0.0,0.0,36.0,36.0,0.0,0.0,945714743,250000.0,NaN,149492.0,NaN,NaN,9.457147e+07,9.502432e+07,2.269000e+05,8.506904e+06,1458500.0,922782493,улучшенная черновая,3.0,2021-07-21,72,0.0,ДПГ-21-06-018/072,0.0,2024-02-26 09:00:35.388555,0.0,2024-03-08 16:16:36.330524,NaN,Гарантия выдана до 2023,2020-12-31,5.044000e+10,2020-12-31,6.167604e+08,4.804272e+08,780424.00,2.305773e+08,3.423439e+08,1.820937e+09,2.165586e+09,1.150793e+10,5.145517e+09,1.150793e+10,3.089054e+08,2.429406e+08,1.280199e+08,0.00,2.429406e+08,0.00,1.283775,0.481567,0.001624,5.319030,0.188182,5.894806,0.021111,0.047214,0.112182,2.236496,0.447128,1.0,0.024880,inf,1.897679,0,376,2024-11-01,1363,3.625000,0
219,111,NaN,6.074000e+10,60740002715,6.074000e+10,NaN,5.054001e+10,2.102400e+11,Завершенный,2021-04-27,Алматинская обл.,24184,Стандартный,"7, 8",Строительство ИКИ за счет средств собственных ...,19.0,2021-03-05,2021-11-10,4,8999.00,1.0,9.0,11439.20,363.00,0.00,234,10.0,0.0,180.0,54.0,0.0,0.0,2271535493,305000.0,NaN,198575.0,400000.0,NaN,2.271535e+08,3.737657e+08,4.734088e+08,1.897770e+07,1458500.0,2271535493,чистовая,2.7,2021-06-09,63,0.0,ДПГ-21-02-028/063,0.0,2024-02-26 09:00:35.388555,0.0,2024-03-08 16:16:36.330524,NaN,Гарантия выдана до 2023,2020-12-31,6.074000e+10,2020-12-31,6.181564e+06,4.115238e+06,219548.00,8.805400e+04,5.156434e+06,7.373320e+05,1.170096e+06,2.017238e+07,3.866254e+06,2.017238e+07,1.181448e+06,1.386600e+05,NaN,1000000.00,1.350000e+05,0.00,1.502116,0.074747,0.053350,0.142993,0.058005,0.624092,0.006692,0.034918,0.115375,5.217551,0.191661,1.0,NaN,inf,NaN,0,250,2024-11-01,1337,5.348000,0
220,2,NaN,3.114000e+10,111140016064,2.064000e+10,NaN,1.402400e+11,2.106400e+11,Завершенный,2022-02-24,Акмолинская обл.,177396,Стандартный,10,Строительство ИКИ за счет собственных средств ...,6.0,2021-11-15,2022-04-05,3,8639.40,4.0,5.0,12721.20,0.00,0.00,190,0.0,0.0,95.0,65.0,25.0,5.0,1748059800,250000.0,NaN,137413.0,NaN,NaN,1.748060e+08,6.626053e+08,1.500000e+05,1.085454e+07,1531500.0,1748059801,черновая,3.0,2022-03-15,109,0.0,ДПГ 22-03-049/109,0.0,2024-02-26 09:00:35.388555,0.0,2024-03-08 16:16:36.330524,NaN,Гарантия выдана до 2023,2021-12-31,1.111400e+11,2021-12-31,6.901348e+06,3.238920e+05,3016.00,2.262664e+06,0.000000e+00,4.698356e+06,4.019520e+06,8.022304e+06,6.379768e+06,8.022304e+06,1.096000e+04,1.014255e+07,0.000000e+00,0.00,4.020240e+05,9756784.00,21.307559,6.995171,0.009312,inf,0.501043,428.682117,0.050113,0.063015,0.100018,1.257460,0.795254,1.0,0.000000,1.039538,inf,0,141,2024-11-01,1082,7.673759,0
221,131,NaN,7.074000e+10,901040000029,9.010400e+11,7.074000e+10,6.064000e+10,1.808400e+11,Действующий,2022-06-10,г. Астана,18178,Стандартный,NaN,Строительство инженерных сетей за счет средств...,15.0,2021-11-26,2023-02-26,4,72945.60,4.0,9.0,114093.40,8035.65,13826.30,1040,67.0,368.0,320.0,400.0,272.0,48.0,21841445585,376000.0,NaN,191435.0,464000.0,2000000.0,3.276217e+09,2.121363e+09,7.150000e+04,1.972008e+08,1531500.0,21841445585,черновая,3.0,2022-07-22,115,0.0,ДПГ-22-01-053/115,NaN,2024-02-26 09:00:35.388555,0.0,2024-03-08 16:16:36.330524,NaN,Гарантия выдана до 2023,2021-12-31,9.010400e+11,2021-12-31,4.444568e+07,3.884904e+07,481032.00,1.734574e+06,3.442990e+06,1.178325e+07,1.331547e+07,9.006396e+07,1.714532e+06,9.006396e+07,5.157142e+06,1.217778e+06,0.000000e+00,11264966.00,1.209970e+06,0.00,1.144061,0.057031,0.012382,3.422389,0.147845,2.284841,0.013435,0.705714,0.090870,52.529763,0.019037,1.0,6.570286,inf,0.108103,1,457,2024-11-01,1071,2.343545,0

In [206]:
# Unfin_cost and Season of every year

def get_season(date):
    month = date.month if pd.notnull(date) else None
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    elif month in [9, 10, 11]:
        return 'Fall'
    else:
        return None

df['season'] = df['dpg_date'].apply(get_season)
df['unfin_coff'] = df['unfin_cost']/df['cost_plan']

In [207]:
# Inflaction of every year 8%

annual_inflation_rate = 0.08
inflation_reference_date = datetime(2024, 11, 1)


df['dpg_date'] = pd.to_datetime(df['dpg_date'], errors='coerce')

financial_columns = [
    'cost_plan', 'flat_msprice', 'build_mscost', 'flat_mscost', 'com_msprice', 'park_price',
    'self_cost', 'unfin_cost', 'share_cost', 'warr_cost', 'comm_cost', 'cost_official',
    'Итого краткосрочные активы', 'Итого краткосрочных обязательств', 'Денежные средства',
    'Краткосрочная дебиторская задолженность', 'Запасы', 'Себестоимость', 'Доход от реализации',
    'Итого активы', 'Итого капитал', 'Итого пассивы', 'Краткосрочная кредиторская задолженность',
    'Операционная прибыль', 'Долгосрочные финансовые обязательства', 'Краткосрочные финансовые обязательства',
    'Итоговая прибыль (убыток)', 'Расходы на финансирование'
]

df['years_since_dpg'] = (inflation_reference_date - df['dpg_date']).dt.days / 365.25
df['inflation_factor'] = (1 + annual_inflation_rate) ** df['years_since_dpg']

for col in financial_columns:
    if col in df.columns:
        df[col] = df[col] * df['inflation_factor']

df.drop(columns=['years_since_dpg', 'inflation_factor'], inplace=True)

In [208]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

df.replace([np.inf, -np.inf], np.nan, inplace=True)

df = df[:-11]
df = df.drop(columns=['application_name', 'author_id', 'engine_id', 'manager_id', 'status', 'decision_date',
                          'region_name', 'build_mscost', 'dpg_num_text', 'prolongation', 'update_date', 'state_id',
                          'create_date', 'annul_date', 'state_name', 'дата фин данных', 'life_cycle', 'today',
                          'gara_id', 'contractor_id', 'designer_id', 'build_qty', 'real_life_cycle', 'bin', 
                          'date', 'start_date', 'end_date', 'turn', 'network', 'Коэффициент долговой нагрузки', 
                          'dpg_add_num', 'dpg_num', 'dpg_date'])

df['coff_doxoda_ot_real'] = df['Доход от реализации'] / df['cost_plan']

df = df[df['type'] != 'Паркинг']

df = df.drop(columns=['type'])


df.replace([np.inf, -np.inf], np.nan, inplace=True)
df = df.drop('Target 2', axis = 1)
df = df.dropna(axis=1, how='all')

non_numeric_cols = df.columns[(df.nunique() < 40) & (df.columns != 'Target')]

label_encoder = LabelEncoder()
for col in non_numeric_cols:
    df[col] = label_encoder.fit_transform(df[col].astype(str))

In [209]:
df.columns

Index(['builder_id', 'city_id', 'period_month', 'class', 'flat_area',
       'build_floor', 'build_area', 'com_area', 'park_area', 'flat_qty',
       'com_qty', 'park_qty', 'flat_onerm', 'flat_tworm', 'flat_threerm',
       'flat_fourrm', 'cost_plan', 'flat_msprice', 'flat_mscost',
       'com_msprice', 'park_price', 'self_cost', 'unfin_cost', 'share_cost',
       'warr_cost', 'comm_cost', 'cost_official', 'flat_inner', 'flat_height',
       'Итого краткосрочные активы', 'Итого краткосрочных обязательств',
       'Денежные средства', 'Краткосрочная дебиторская задолженность',
       'Запасы', 'Себестоимость', 'Доход от реализации', 'Итого активы',
       'Итого капитал', 'Итого пассивы',
       'Краткосрочная кредиторская задолженность', 'Операционная прибыль',
       'Долгосрочные финансовые обязательства',
       'Краткосрочные финансовые обязательства', 'Итоговая прибыль (убыток)',
       'Расходы на финансирование', 'Коэффициент текущей ликвидности',
       'Коэффициент быстрой ликвидности', 'Коэффициент абсолютной ликвидности',
       'Коэффициент оборачиваемости запасов',
       'Коэффициент оборачиваемости активов',
       'Коэффициент оборачиваемости кредиторской задолженности', 'ROA', 'ROE',
       'Коэффициент чистой прибыли', 'Коэффициент финансового левериджа',
       'Коэффициент финансовой независимости', 'Коэффициент долг на капитал',
       'Коэффициент покрытия процентов', 'Покрытие долга', 'Target',
       'percent_of_life_cycle', 'season', 'unfin_coff', 'coff_doxoda_ot_real'],
      dtype='object')

In [210]:
df.to_excel('df.xlsx')

In [211]:
pd.set_option('display.max_columns', None)
if df[col].dtype == 'object':
    df[col] = df[col].str.replace(',', '')
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

In [212]:
df.replace(np.NaN, 0, inplace=True)

In [213]:
df[non_numeric_cols] = df[non_numeric_cols].astype(str)

In [214]:
iv_score_dict = {}
for col in tqdm(X.columns):
    if col in cat_cols:
        optb = optbinning.OptimalBinning(dtype='categorical')
        optb.fit(df[col], df['Target'])
    else:
        optb = optbinning.OptimalBinning(dtype='numerical')
        optb.fit(df[col], df['Target'])
    binning_table = optb.binning_table
    binning_table.build()
    iv_score_dict[col] = binning_table.iv
iv_score_df = pd.Series(iv_score_dict)
iv_score_df.sort_values(ascending=False, inplace=True)

100%|██████████████████████████████████████████████████████████████████████████████████| 63/63 [00:03<00:00, 16.16it/s]

In [215]:
pd.set_option('display.max_columns', None)

In [216]:
iv_score_df

Коэффициент оборачиваемости активов       1.283359
period_month                              1.175856
city_id                                   0.954683
share_cost                                0.937570
Итого краткосрочные активы                0.612790
                                            ...
self_cost                                 0.131563
Краткосрочные финансовые обязательства    0.126889
Коэффициент долг на капитал               0.082434
park_price                                0.074951
class                                     0.020817
Length: 63, dtype: float64

In [217]:
iv_score_df2 = pd.DataFrame(iv_score_df, columns=['Numbers']).reset_index()
iv_score_df3 = iv_score_df2[iv_score_df2['Numbers'].between(0.5, 2)]
selected_features = iv_score_df3['index']
selected_features

0          Коэффициент оборачиваемости активов
1                                 period_month
2                                      city_id
3                                   share_cost
4                   Итого краткосрочные активы
5                        percent_of_life_cycle
6                                 Итого активы
7                                Итого пассивы
8                    Расходы на финансирование
9                                      com_qty
10    Краткосрочная кредиторская задолженность
11                                         ROE
12                                 build_floor
13                        Операционная прибыль
14                                         ROA
Name: index, dtype: object

In [218]:
df2 = pd.concat([df[selected_features], df['Target']], axis = 1)
X = df2.drop(['Target'], axis = 1)
y = df2['Target']
X_train, y_train, X_test, y_test = train_test_split(X, y, test_size = 0.35, random_state = 42)

In [219]:
from sklearn import linear_model

binning_process = optbinning.BinningProcess(
  variable_names=X.columns.to_list())
# estimator
estimator = LogisticRegression()
scorecard = optbinning.Scorecard(
  binning_process=binning_process,
  estimator=estimator,
  scaling_method="min_max",
  scaling_method_params={"min": 300, "max": 850},

)

In [221]:
scorecard.fit(X, y)

Scorecard(binning_process=BinningProcess(variable_names=['Коэффициент '
                                                         'оборачиваемости '
                                                         'активов',
                                                         'period_month',
                                                         'city_id',
                                                         'share_cost',
                                                         'Итого краткосрочные '
                                                         'активы',
                                                         'percent_of_life_cycle',
                                                         'Итого активы',
                                                         'Итого пассивы',
                                                         'Расходы на '
                                                         'финансирование',
                                                         'com_qty',
                                                         'Краткосрочная '
                                                         'кредиторская '
                                                         'задолженность',
                                                         'ROE', 'build_floor',
                                                         'Операционная прибыль',
                                                         'ROA']),
          estimator=LogisticRegression(), scaling_method='min_max',
          scaling_method_params={'max': 850, 'min': 300})

In [222]:
scorecard.intercept_

0

In [223]:
scorecard_df = scorecard.table(style="detailed")

In [224]:
len(scorecard_df['Variable'].unique())

15

In [225]:
scorecard_df.to_excel('scorecard.xlsx')

In [226]:
prediction = scorecard.predict_proba(X)[:, 1]
print(f'Logit ROC_AUC: {roc_auc_score(y, prediction )}')

Logit ROC_AUC: 0.980186702228996

In [227]:
scorecard_df2 = scorecard_df.drop_duplicates(subset=['Variable'])
scorecard_df2= scorecard_df2[['Variable', 'Coefficient']]
scorecard_df2

                                   Variable  Coefficient
0       Коэффициент оборачиваемости активов    -0.541506
0                              period_month    -0.527451
0                                   city_id    -1.180631
0                                share_cost    -0.893418
0                Итого краткосрочные активы    -0.387786
0                     percent_of_life_cycle    -0.541681
0                              Итого активы    -0.421593
0                             Итого пассивы    -0.421593
0                 Расходы на финансирование    -0.193153
0                                   com_qty    -0.454107
0  Краткосрочная кредиторская задолженность     0.280909
0                                       ROE    -0.400167
0                               build_floor    -1.153219
0                      Операционная прибыль    -0.674129
0                                       ROA     0.033091