In [46]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_excel('fin_data_of_proj.xlsx')
df = df[:-11]
df

,Unnamed: 0,gara_id,application_name,author_id,builder_id,contractor_id,designer_id,engine_id,manager_id,status,...,Коэффициент долговой нагрузки,Коэффициент долг на капитал,Коэффициент покрытия процентов,Покрытие долга,Target,life_cycle,today,real_life_cycle,percent_of_lifi_cycle,percent_of_life_cycle
0,0,729352,Заявка на гарантирование - 335,5.400012e+08,960340000376,9.603400e+11,0.0,2.210400e+11,1.904400e+11,NaN,...,1.0,0.060174,5.733126,3.488284,0,395,2024-11-01,729,1.845570,1.845570
1,1,790750,Заявка на гарантирование - 334,4.044001e+10,960340000376,9.603400e+11,0.0,2.210400e+11,1.904400e+11,NaN,...,1.0,0.060174,5.733126,3.488284,0,639,2024-11-01,729,1.140845,1.140845
2,2,845821,Заявка на гарантирование - 407,8.034001e+10,60340004172,6.034000e+10,0.0,1.304400e+11,2.109400e+11,NaN,...,1.0,0.929396,20.794199,0.550207,0,274,2024-11-01,508,1.854015,1.854015
3,3,781580,Заявка на гарантирование - 379,5.114001e+10,981040003722,9.810400e+11,0.0,7.054001e+10,2.109400e+11,NaN,...,1.0,0.020449,1331.828571,5.548625,0,426,2024-11-01,742,1.741784,1.741784
4,4,746713,Заявка на гарантирование - 373,9.207400e+11,80440009616,8.044001e+10,0.0,2.208400e+11,2.202400e+11,NaN,...,1.0,0.000000,inf,inf,0,275,2024-11-01,575,2.090909,2.090909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,214,1152403,Заявка на гарантирование - 484,1.704400e+11,131240018048,1.312400e+11,0.0,2.003400e+11,1.709400e+11,NaN,...,1.0,0.000000,26.373242,inf,0,365,2024-11-01,246,0.673973,0.673973
207,215,1130533,Заявка на гарантирование - 478,8.104000e+10,50640012251,5.064001e+10,0.0,2.111400e+11,2.201400e+11,NaN,...,1.0,0.331792,inf,0.823126,0,305,2024-11-01,281,0.921311,0.921311
208,216,1124311,Заявка на гарантирование - 476,7.074002e+10,170840003753,1.708400e+11,0.0,1.411400e+11,2.004400e+11,NaN,...,1.0,5.479264,-inf,-0.039945,0,701,2024-11-01,324,0.462197,0.462197
209,217,1159397,Заявка на гарантирование - 485,3.104000e+10,31040001233,3.104000e+10,0.0,1.607400e+11,2.401400e+11,NaN,...,1.0,0.000000,inf,inf,0,304,2024-11-01,183,0.601974,0.601974
210,218,1175915,Заявка на гарантирование - 486,3.104000e+10,31040001233,3.104000e+10,0.0,1.607400e+11,2.402400e+11,NaN,...,1.0,0.000000,inf,inf,0,304,2024-11-01,158,0.519737,0.519737

In [48]:
df = df.drop(['Unnamed: 0', 'application_name', 'author_id', 'contractor_id', 'designer_id', 'engine_id', 'status',
              'decision_date', 'region_name', 'type', 'turn', 'period_month', 'build_qty', 'share_cost', 'comm_cost',
              'prolongation', 'state_id', 'annul_date', 'state_name', 'дата фин данных', 'percent_of_lifi_cycle'], axis=1)

## Models Testing

In [79]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix, 
    roc_auc_score, roc_curve
)

# Define the target variable (y) and features (X)
y = df['Target']
X = df.drop(columns=['Target'])
X.replace([np.inf, -np.inf], np.nan, inplace=True)

# Identify non-numeric columns
non_numeric_cols = X.select_dtypes(include=['object', 'datetime', 'timedelta']).columns

# Apply LabelEncoder to non-numeric columns           
label_encoder = LabelEncoder()
for col in non_numeric_cols:
    X[col] = label_encoder.fit_transform(X[col].astype(str))

# Handle missing values using SimpleImputer (fill with median)
imputer = SimpleImputer(strategy='median')
X_imputed_encoded = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_imputed_encoded, y, test_size=0.2, random_state=42)

# Initialize ensemble models
models = {
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Bagging": BaggingClassifier(),
}

# Train models and collect predictions and feature importances
feature_importances = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    
    # Store feature importance if available
    if hasattr(model, 'feature_importances_'):
        feature_importances[name] = model.feature_importances_

    # Predict and evaluate
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]
    
    print(f"{name} Accuracy: {accuracy_score(y_test, y_pred):.2f}")
    print(f"{name} Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
    print(f"{name} ROC AUC: {roc_auc_score(y_test, y_prob):.2f}\n")


plt.tight_layout()
plt.show()

Random Forest Accuracy: 0.86
Random Forest Confusion Matrix:
[[36  0]
 [ 6  1]]

Random Forest ROC AUC: 0.79

Gradient Boosting Accuracy: 0.81
Gradient Boosting Confusion Matrix:
[[34  2]
 [ 6  1]]

Gradient Boosting ROC AUC: 0.75

AdaBoost Accuracy: 0.72
AdaBoost Confusion Matrix:
[[30  6]
 [ 6  1]]

AdaBoost ROC AUC: 0.52

Bagging Accuracy: 0.86
Bagging Confusion Matrix:
[[36  0]
 [ 6  1]]

Bagging ROC AUC: 0.58

C:\Users\Norynbayev\AppData\Local\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

## Feature Importance

In [67]:
from matplotlib.backends.backend_pdf import PdfPages

num_features = X.shape[1]
fig, axes = plt.subplots(len(feature_importances), 1, figsize=(40, 20 * len(feature_importances)))

with PdfPages("feature_importances.pdf") as pdf:
    for idx, (name, importance) in enumerate(feature_importances.items()):
        axes[idx].barh(X.columns, importance)
        axes[idx].set_title(f"{name} Feature Importance")
        axes[idx].set_xlabel("Importance Score")
        axes[idx].set_ylabel("Features")
        
    pdf.savefig(fig)
    plt.close(fig)

In [68]:
X_test

,gara_id,builder_id,manager_id,city_id,network,start_date,end_date,class,flat_area,build_floor,...,Коэффициент финансового левериджа,Коэффициент финансовой независимости,Коэффициент долговой нагрузки,Коэффициент долг на капитал,Коэффициент покрытия процентов,Покрытие долга,life_cycle,today,real_life_cycle,percent_of_life_cycle
30,198.0,9.603400e+11,1.606400e+11,18194.0,4.0,6.0,5.0,4.0,8948.40,65.0,...,5.236752,0.190958,1.000000,0.623296,-3.579692,-0.091385,516.0,0.0,2481.0,4.808140
173,93.0,1.034000e+10,2.002400e+11,18277.0,20.0,88.0,103.0,4.0,18955.35,48.0,...,8.638802,0.115757,1.000000,0.295723,1.522332,0.608822,671.0,0.0,1288.0,1.919523
140,43.0,6.014000e+10,1.702400e+11,18178.0,4.0,11.0,17.0,4.0,12015.51,65.0,...,18.578259,0.053826,1.000000,0.000000,1.522332,0.155298,708.0,0.0,2328.0,3.288136
75,7.0,1.105400e+11,1.906400e+11,18194.0,3.0,34.0,45.0,4.0,22101.80,18.0,...,11.883087,0.084153,1.000000,0.138312,1.522332,7.945981,695.0,0.0,1866.0,2.684892
60,184.0,9.010400e+11,2.106400e+11,18178.0,3.0,139.0,126.0,4.0,10854.86,39.0,...,52.529763,0.019037,1.000000,6.570286,1.522332,0.108103,365.0,0.0,798.0,2.186301
208,1124311.0,1.708400e+11,2.004400e+11,18194.0,60.0,177.0,184.0,4.0,31440.78,47.0,...,6.597274,0.151578,1.000000,5.479264,1.522332,-0.039945,701.0,0.0,324.0,0.462197
45,194.0,1.106400e+11,1.610400e+11,18194.0,3.0,58.0,78.0,4.0,15350.64,5.0,...,2.993028,0.334110,1.000000,0.238986,1.522332,0.155298,674.0,0.0,1486.0,2.204748
183,1124232.0,1.105400e+11,2.108400e+11,18178.0,59.0,183.0,166.0,4.0,7217.35,48.0,...,5.682418,0.175981,1.000000,1.663461,-819.395349,-0.007622,214.0,0.0,226.0,1.056075
9,892091.0,1.105400e+11,2.108400e+11,18178.0,60.0,163.0,152.0,4.0,16162.59,20.0,...,3.666575,0.272734,1.000000,1.271609,-25.765597,-0.017271,366.0,0.0,518.0,1.415301
100,199.0,6.054001e+10,2.002400e+11,18178.0,31.0,103.0,78.0,4.0,11410.70,48.0,...,2.726757,0.366736,1.000000,0.063511,1.522332,0.070352,400.0,0.0,1212.0,3.030000
137,42.0,1.105400e+11,1.904400e+11,18178.0,38.0,86.0,79.0,4.0,17864.97,48.0,...,5.030034,0.198806,1.000000,0.238986,1.522332,0.155298,490.0,0.0,1295.0,2.642857
204,1029222.0,9.603400e+11,1.904400e+11,18178.0,59.0,172.0,161.0,4.0,7198.20,44.0,...,1.163885,0.859191,1.000000,0.060174,5.733126,3.488284,366.0,0.0,422.0,1.153005
156,137.0,9.603400e+11,1.706400e+11,18178.0,4.0,25.0,33.0,4.0,17108.30,48.0,...,5.244920,0.190661,1.000000,0.573961,-0.374007,-0.034208,670.0,0.0,1962.0,2.928358
82,75.0,1.105400e+11,1.303400e+11,18178.0,2.0,9.0,6.0,4.0,24008.28,65.0,...,13.983508,0.071513,1.000000,0.238986,1.522332,0.155298,473.0,0.0,2367.0,5.004228
15,191.0,1.606400e+11,2.111400e+11,18194.0,31.0,125.0,162.0,4.0,83919.90,28.0,...,5.030034,0.198806,1.000000,0.238986,1.522332,0.155298,974.0,0.0,1022.0,1.049281
200,809374.0,1.111400e+11,2.110400e+11,177396.0,59.0,158.0,167.0,4.0,14028.40,36.0,...,1.062949,0.940779,1.000000,0.000000,1.522332,0.155298,583.0,0.0,592.0,1.015437
167,37.0,8.044001e+10,2.202400e+11,-11.0,11.0,130.0,97.0,4.0,2544.20,36.0,...,2.654469,0.376723,1.000000,0.164598,1.522332,1.730248,306.0,0.0,948.0,3.098039
18,142.0,1.034000e+10,1.901400e+11,18277.0,3.0,25.0,24.0,3.0,7644.60,36.0,...,8.500254,0.117644,1.000000,0.269398,1.522332,0.391145,488.0,0.0,1962.0,4.020492
209,1159397.0,3.104000e+10,2.401400e+11,18274.0,59.0,184.0,177.0,4.0,10974.61,36.0,...,1.807297,0.553313,1.000000,0.000000,1.522332,0.155298,304.0,0.0,183.0,0.601974
86,143.0,9.603400e+11,1.603400e+11,18178.0,4.0,143.0,144.0,4.0,7356.90,17.0,...,1.163885,0.859191,1.000000,0.060174,5.733126,3.488284,517.0,0.0,744.0,1.439072
79,88.0,1.105400e+11,1.811400e+11,18178.0,63.0,97.0,102.0,4.0,15784.90,56.0,...,9.506222,0.105194,1.000000,0.781308,1.522332,0.056486,610.0,0.0,1234.0,2.022951
55,20.0,7.024002e+10,1.910400e+11,18267.0,38.0,99.0,150.0,4.0,66111.10,36.0,...,17.457896,0.057281,1.000000,0.238986,9.397917,0.155298,1064.0,0.0,1227.0,1.153195
148,202.0,9.603400e+11,1.708400e+11,18178.0,29.0,22.0,29.0,4.0,9242.00,31.0,...,5.244920,0.190661,1.000000,0.573961,-0.374007,-0.034208,580.0,0.0,1983.0,3.418966
206,1152403.0,1.312400e+11,1.709400e+11,18178.0,60.0,181.0,176.0,4.0,66054.54,60.0,...,2.829602,0.353407,1.000000,0.000000,26.373242,0.155298,365.0,0.0,246.0,0.673973
150,193.0,9.603400e+11,1.708400e+11,18178.0,3.0,21.0,36.0,4.0,13955.10,48.0,...,5.244920,0.190661,1.000000,0.573961,-0.374007,-0.034208,731.0,0.0,1984.0,2.714090
143,96.0,9.807400e+11,1.611400e+11,18178.0,3.0,10.0,34.0,4.0,11540.44,37.0,...,39.608142,0.025247,1.000000,3.189655,12.769336,1.024835,1050.0,0.0,2331.0,2.220000
25,58.0,9.603400e+11,2.009400e+11,18194.0,52.0,128.0,160.0,4.0,12056.90,5.0,...,1.598479,0.625595,1.000000,0.246676,3.841915,0.559076,915.0,0.0,975.0,1.065574
104,47.0,2.124001e+10,2.008400e+11,18178.0,9.0,65.0,88.0,4.0,10735.96,40.0,...,16.189439,0.061769,1.000000,0.238986,1.522332,0.155298,700.0,0.0,1422.0,2.031429
16,160.0,1.106400e+11,1.708400e+11,18194.0,3.0,56.0,66.0,4.0,13262.80,17.0,...,2.993028,0.334110,1.000000,0.238986,1.522332,0.155298,628.0,0.0,1507.0,2.399682
177,116.0,6.024003e+10,2.211400e+11,18277.0,54.0,149.0,134.0,4.0,6432.11,36.0,...,6.010237,0.166383,1.000000,0.000000,1.522332,0.155298,365.0,0.0,694.0,1.901370
135,74.0,1.105400e+11,1.103400e+11,18178.0,18.0,81.0,91.0,4.0,19606.32,48.0,...,9.506222,0.105194,1.000000,0.781308,1.522332,0.056486,624.0,0.0,1327.0,2.126603
126,145.0,9.603400e+11,1.806400e+11,18178.0,3.0,31.0,28.0,4.0,10679.10,50.0,...,5.244920,0.190661,1.000000,0.573961,-0.374007,-0.034208,481.0,0.0,1885.0,3.918919
109,174.0,1.105400e+11,1.909400e+11,18178.0,4.0,53.0,49.0,4.0,12790.19,48.0,...,8.589468,0.116422,1.000000,0.059460,1.522332,-0.159966,476.0,0.0,1596.0,3.352941
68,48.0,5.064001e+10,1.901400e+11,18178.0,24.0,62.0,105.0,4.0,9172.79,48.0,...,16.883407,0.059230,1.000000,0.000000,1.522332,0.155298,819.0,0.0,1431.0,1.747253
73,23.0,9.603400e+11,1.606400e+11,18194.0,4.0,12.0,9.0,4.0,7831.90,65.0,...,5.236752,0.190958,1.000000,0.623296,-3.579692,-0.091385,542.0,0.0,2317.0,4.274908
147,151.0,9.603400e+11,1.708400e+11,18178.0,3.0,47.0,43.0,4.0,5621.99,23.0,...,5.244920,0.190661,1.000000,0.573961,-0.374007,-0.034208,442.0,0.0,1641.0,3.712670
181,911326.0,5.064001e+10,2.107400e+11,18277.0,59.0,170.0,153.0,4.0,9734.34,36.0,...,3.962230,0.252383,1.000000,0.104708,1.522332,3.738441,305.0,0.0,452.0,1.481967
96,81.0,1.701400e+11,2.101400e+11,18178.0,40.0,76.0,70.0,4.0,26037.30,51.0,...,2.114496,0.472926,1.000000,0.027286,1.522332,0.067112,494.0,0.0,1357.0,2.746964
189,1312620.0,9.603400e+11,1.902400e+11,18178.0,60.0,185.0,181.0,4.0,10791.17,23.0,...,1.200777,0.832794,1.000000,0.100673,3.992467,1.392759,426.0,0.0,182.0,0.427230
93,121.0,1.105400e+11,1.106400e+11,18178.0,48.0,152.0,144.0,4.0,8146.55,48.0,...,3.666575,0.272734,1.000000,1.271609,-25.765597,-0.017271,425.0,0.0,652.0,1.534118
115,195.0,1.606400e+11,1.609400e+11,18194.0,31.0,107.0,72.0,4.0,39500.80,36.0,...,2.301907,0.434422,1.000000,0.000000,1.522332,0.155298,331.0,0.0,1187.0,3.586103
163,22.0,5.044000e+10,1.706400e+11,18264.0,16.0,45.0,30.0,3.0,2075.12,35.0,...,2.939753,0.343371,1.009425,0.001203,32.763162,159.640515,319.0,0.0,1694.0,5.310345
195,816920.0,7.400024e+08,1.904400e+11,18198.0,60.0,166.0,142.0,4.0,15148.34,35.0,...,2.696941,0.370790,1.000000,0.300390,3.154109,0.690626,244.0,0.0,485.0,1.987705

In [74]:
model = RandomForestClassifier(n_estimators = 200, max_depth = 100000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [75]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [71]:
y_test

30     0
173    1
140    0
75     0
60     0
208    0
45     0
183    0
9      1
100    0
137    0
204    0
156    0
82     0
15     0
200    0
167    0
18     0
209    0
86     0
79     0
55     0
148    0
206    0
150    0
143    1
25     1
104    0
16     0
177    1
135    0
126    0
109    0
68     0
73     0
147    0
181    0
96     0
189    0
93     1
115    0
163    0
195    1
Name: Target, dtype: int64