In [1]:
import pandas as pd

In [2]:
df1 = pd.read_excel('Фин данные ДАЙС.xlsx')
df1

,gara_id,bin,parent_id,fin_id,date_id,date,rank_num,name,value,update_date,category,subcategory,role,company_name
0,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year-1,2022-12-31,1124311.0,Краткосрочная дебиторская задолженность,1361507.0,2024-03-27 06:37:34.465619,активы,краткосрочные,Застройщик,"ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""..."
1,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year-2,2021-12-31,1124311.0,Краткосрочная дебиторская задолженность,1400959.0,2024-03-27 06:37:34.465619,активы,краткосрочные,Застройщик,"ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""..."
2,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year_current,2023-12-31,1124311.0,Краткосрочная дебиторская задолженность,6100.0,2024-03-27 06:37:34.465619,активы,краткосрочные,Застройщик,"ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""..."
3,1124311,1.708400e+11,3.0,2001-01-01 00:00:00,year-1,2022-12-31,1124311.0,Запасы,795139.0,2024-03-27 06:37:34.465619,активы,краткосрочные,Застройщик,"ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""..."
4,1124311,1.708400e+11,3.0,2001-01-01 00:00:00,year-2,2021-12-31,1124311.0,Запасы,898369.0,2024-03-27 06:37:34.465619,активы,краткосрочные,Застройщик,"ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46547,1397186,1.502400e+11,24.0,1.4.1.4,year_current,2024-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),36764.0,2024-09-27 09:00:00.883837,ДДС. Итого,итого (увеличение + / - уменьшение ДС),Застройщик,"ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""..."
46548,1397186,1.502400e+11,24.0,1.4.1.4,year-1,2023-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-2306.0,2024-09-11 18:00:00.644409,ДДС. Итого,итого (увеличение + / - уменьшение ДС),Застройщик,"ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""..."
46549,1397186,1.502400e+11,24.0,1.4.1.4,year-1,2023-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-2306.0,2024-09-27 09:00:00.883837,ДДС. Итого,итого (увеличение + / - уменьшение ДС),Застройщик,"ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""..."
46550,1397186,1.502400e+11,24.0,1.4.1.4,year-2,2022-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-322.0,2024-09-11 18:00:00.644409,ДДС. Итого,итого (увеличение + / - уменьшение ДС),Застройщик,"ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""..."
46551,1397186,1.502400e+11,24.0,1.4.1.4,year-2,2022-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-322.0,2024-09-27 09:00:00.883837,ДДС. Итого,итого (увеличение + / - уменьшение ДС),Застройщик,"ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""..."

In [3]:
df2 = pd.read_excel('Данные о проектах.xlsx')
df2

,gara_id,application_name,author_id,builder_id,contractor_id,designer_id,engine_id,manager_id,status,decision_date,...,flat_height,dpg_date,dpg_num,dpg_add_num,dpg_num_text,prolongation,update_date,state_id,create_date,annul_date
0,1027137,Заявка на гарантирование -,0,0.000000e+00,0,0,0.000000e+00,0.000000e+00,NaN,NaN,...,NaN,2024-01-04,NaN,NaN,NaN,NaN,2024-02-27 09:11:05.726551,15463.0,2024-03-08 16:16:36.330524,NaT
1,1242930,Заявка на гарантирование - 487,70440008408,1.104400e+11,110440011339,0,2.103400e+11,2.011400e+11,NaN,NaN,...,NaN,2024-05-31,NaN,NaN,NaN,NaN,2024-05-03 15:00:01.182421,20943.0,2024-04-26 15:00:01.82722,NaT
2,1149569,Заявка на гарантирование - 483,60440000659,9.705400e+11,970540007997,0,2.010400e+11,3.094000e+10,NaN,NaN,...,NaN,2024-03-25,NaN,NaN,NaN,NaN,2024-03-12 11:59:36.457081,20943.0,2024-03-08 16:16:36.330524,NaT
3,729352,Заявка на гарантирование - 335,540001174,9.603400e+11,960340000376,0,2.210400e+11,1.904400e+11,NaN,NaN,...,NaN,2023-06-21,58.0,7.0,ДС7 21.06.23 к ДПГ-21-01-001/058,NaN,2024-06-04 14:03:30.466878,15320.0,2024-03-08 16:16:36.330524,NaT
4,790750,Заявка на гарантирование - 334,40440008640,9.603400e+11,960340000376,0,2.210400e+11,1.904400e+11,NaN,NaN,...,NaN,2023-08-11,54.0,9.0,дс9 11.08.23 к ДПГ-21-01-001/054,NaN,2024-06-04 14:03:30.466878,15320.0,2024-03-08 16:16:36.330524,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,",0""",0,0,0.000000e+00,0,0,0.000000e+00,0.000000e+00,0,0,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
311,2,NaN,31140001495,1.111400e+11,20640000573,NaN,1.402400e+11,2.106400e+11,Завершенный,2022-02-24 00:00:00,...,NaN,2022-03-15,109.0,0.0,ДПГ 22-03-049/109,0.0,2024-02-26 09:00:35.388555,0.0,2024-03-08 16:16:36.330524,NaT
312,131,NaN,70740004674,9.010400e+11,901040000029,70740004674,6.064000e+10,1.808400e+11,Действующий,2022-06-10 00:00:00,...,3.0,2022-07-22,115.0,0.0,ДПГ-22-01-053/115,NaN,2024-02-26 09:00:35.388555,0.0,2024-03-08 16:16:36.330524,NaT
313,1318319,Заявка на гарантирование - 493,170440036256,1.312400e+11,131240018048,0,2.003400e+11,1.709400e+11,NaN,NaN,...,NaN,2024-08-16,166.0,1.0,дс №1 к ДПГ-24-01-044/166,NaN,2024-09-26 06:00:00.451543,15320.0,2024-06-18 15:00:02.987313,NaT
314,1470655,Заявка на гарантирование - 505,110440013622,7.034001e+10,70340014459,0,1.807400e+11,1.202400e+11,NaN,NaN,...,NaN,2024-10-25,NaN,NaN,NaN,NaN,2024-09-27 06:00:00.642525,20943.0,2024-09-23 06:00:02.429293,NaT

In [4]:
merged_df = pd.merge(df1, df2, left_on='bin', right_on='builder_id', how='left')

In [5]:
merged_df

,gara_id_x,bin,parent_id,fin_id,date_id,date,rank_num,name,value,update_date_x,...,flat_height,dpg_date,dpg_num,dpg_add_num,dpg_num_text,prolongation,update_date_y,state_id,create_date,annul_date
0,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year-1,2022-12-31,1124311.0,Краткосрочная дебиторская задолженность,1361507.0,2024-03-27 06:37:34.465619,...,NaN,2024-04-11,167.0,NaN,ДПГ-24-02-071/167,NaN,2024-04-12 09:00:00.972888,15320.0,2024-03-08 16:16:36.330524,NaT
1,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year-2,2021-12-31,1124311.0,Краткосрочная дебиторская задолженность,1400959.0,2024-03-27 06:37:34.465619,...,NaN,2024-04-11,167.0,NaN,ДПГ-24-02-071/167,NaN,2024-04-12 09:00:00.972888,15320.0,2024-03-08 16:16:36.330524,NaT
2,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year_current,2023-12-31,1124311.0,Краткосрочная дебиторская задолженность,6100.0,2024-03-27 06:37:34.465619,...,NaN,2024-04-11,167.0,NaN,ДПГ-24-02-071/167,NaN,2024-04-12 09:00:00.972888,15320.0,2024-03-08 16:16:36.330524,NaT
3,1124311,1.708400e+11,3.0,2001-01-01 00:00:00,year-1,2022-12-31,1124311.0,Запасы,795139.0,2024-03-27 06:37:34.465619,...,NaN,2024-04-11,167.0,NaN,ДПГ-24-02-071/167,NaN,2024-04-12 09:00:00.972888,15320.0,2024-03-08 16:16:36.330524,NaT
4,1124311,1.708400e+11,3.0,2001-01-01 00:00:00,year-2,2021-12-31,1124311.0,Запасы,898369.0,2024-03-27 06:37:34.465619,...,NaN,2024-04-11,167.0,NaN,ДПГ-24-02-071/167,NaN,2024-04-12 09:00:00.972888,15320.0,2024-03-08 16:16:36.330524,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270671,1397186,1.502400e+11,24.0,1.4.1.4,year_current,2024-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),36764.0,2024-09-27 09:00:00.883837,...,NaN,NaT,NaN,NaN,NaN,NaN,2024-10-14 09:00:00.630897,15311.0,2024-08-06 15:00:01.677535,NaT
270672,1397186,1.502400e+11,24.0,1.4.1.4,year-1,2023-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-2306.0,2024-09-11 18:00:00.644409,...,NaN,NaT,NaN,NaN,NaN,NaN,2024-10-14 09:00:00.630897,15311.0,2024-08-06 15:00:01.677535,NaT
270673,1397186,1.502400e+11,24.0,1.4.1.4,year-1,2023-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-2306.0,2024-09-27 09:00:00.883837,...,NaN,NaT,NaN,NaN,NaN,NaN,2024-10-14 09:00:00.630897,15311.0,2024-08-06 15:00:01.677535,NaT
270674,1397186,1.502400e+11,24.0,1.4.1.4,year-2,2022-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-322.0,2024-09-11 18:00:00.644409,...,NaN,NaT,NaN,NaN,NaN,NaN,2024-10-14 09:00:00.630897,15311.0,2024-08-06 15:00:01.677535,NaT
270675,1397186,1.502400e+11,24.0,1.4.1.4,year-2,2022-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-322.0,2024-09-27 09:00:00.883837,...,NaN,NaT,NaN,NaN,NaN,NaN,2024-10-14 09:00:00.630897,15311.0,2024-08-06 15:00:01.677535,NaT

In [7]:
merged_df.to_csv("Все данные об проекте.csv", index=False)
print("Data saved as CSV.")

Data saved as CSV.